FROM datamechanics/spark:3.2.0-dm16

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

#WORKDIR /opt/application/

#COPY requirements.txt .
#RUN pip3 install --no-cache-dir -r requirements.txt

#COPY src/ src/
#COPY main.py .

#docker build -t spark_taxi_ingest:v002 .
#docker run 